# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# For window rules and layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules 
# This file will not be modified during dotfiles updates

# Define that windows with the class 'floating_yazi' should float
windowrule = match:class ^(floating_yazi)$, float on, center on, size (monitor_w*0.6) (monitor_h*0.7)

# CopyQ preferences and main window
windowrule = match:class ^(com.github.hluk.copyq)$, float on, center on, size (monitor_w*0.6) (monitor_h*0.7)

# Rofi menus and wallpaper tools
windowrule = match:tag wallpaper, float on, center on, size (monitor_w*0.6) (monitor_h*0.7)
windowrule = match:class ^([Rr]ofi)$, size (monitor_w*0.5) (monitor_h*0.6)
