# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #FDF7FA
background         #1E1A1D
cursor             #998697

active_tab_foreground     #1E1A1D
active_tab_background     #FDF7FA
inactive_tab_foreground   #FDF7FA
inactive_tab_background   #1E1A1D

active_border_color   #FDF7FA
inactive_border_color #1E1A1D
bell_border_color     #1F0F1D

color0      #454144
color1		#1F0F1D
color2		#281027
color3		#2E112D
color4		#6A1D6C
color5		#88238C
color6		#BBAEB5
color7		#F4EBF0
color8		#AAA4A8
color9		#291426
color10		#351634
color11		#3D173C
color12		#8D2690
color13		#B52EBA
color14		#F9E8F1
color15		#F4EBF0
