# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1E1A1D)
$foreground = rgb(FDF7FA)
$color0 = rgb(454144)
$color1 = rgb(1F0F1D)
$color2 = rgb(281027)
$color3 = rgb(2E112D)
$color4 = rgb(6A1D6C)
$color5 = rgb(88238C)
$color6 = rgb(BBAEB5)
$color7 = rgb(F4EBF0)
$color8 = rgb(AAA4A8)
$color9 = rgb(291426)
$color10 = rgb(351634)
$color11 = rgb(3D173C)
$color12 = rgb(8D2690)
$color13 = rgb(B52EBA)
$color14 = rgb(F9E8F1)
$color15 = rgb(F4EBF0)
